---
name: "Next in Series"
guid: "12345678-9abc-def0-1234-56789abcdef0"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Automatically queue next movie in series to Continue Watching"
description: >
  This plugin automatically detects when you finish watching a movie
  and adds the next movie in the series/collection to your Continue Watching list.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.NextInSeries.dll"
changelog: >
  changelog
